version: '2.3'
services:

  prometheus:
    image: ${REGISTRY}/hub/prom/prometheus:v2.4.3
    container_name: prometheus
    hostname: prometheus
    extra_hosts:
      - 'influxdb:${INFLUXDB}'
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/config:/config:ro
    command:
      - --config.file=/config/prometheus.yml
      - --web.enable-lifecycle
    restart: always
    cpu_count: 2
    mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    