#cloud-config
hostname: 'gitlab.test.tj.itc.inventec'

users:
  - name: 'prod'
    groups:
      - 'sudo'
      - 'docker'

coreos:
  units:
    - name: docker.service
      command: start
      enable: true
    - name: update-engine.service
      command: stop
    - name: locksmithd.service
      command: stop
  update:
    reboot-strategy: off

write-files:
  - path: '/etc/systemd/system/sshd.socket.d/10-sshd-port.conf'
    permissions: '0644'
    owner: 'root'
    content: |
      [Socket]
      ListenStream=
      ListenStream=23

  - path: '/etc/timezone'
    content: |
      Asia/Shanghai

  - path: '/etc/systemd/timesyncd.conf'
    content: |
      [Time]
      NTP=10.190.1.10 10.190.1.15

  - path: '/etc/systemd/system/docker.service.d/http-proxy.conf'
    content: |
      [Service]
      Environment=

  - path: '/etc/hosts'
    content: |
      127.0.0.1       localhost
      ::1             localhost
      10.190.81.222   registry.inventec

  - path: '/etc/docker/daemon.json'
    content: |
      {
        "live-restore": true,
        "insecure-registries" : ["registry.inventec"]
      }
