version: "3.3"
services:

  sparkmaster:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkmaster
    volumes:
      - /opt/spark/tasks:/opt/tasks
      - /data/ssd0/spark/spark-events:/tmp/spark-events
    environment:
      SPARK_PUBLIC_DNS: 10.99.170.13
      SPARK_MASTER_WEBUI_PORT: 18081
      SPARK_LOCAL_DIRS: /tmp
    networks:
      hostnet: {}
    extra_hosts:
      - "sparkmaster:10.99.170.13"
      - "sparkw1:10.99.170.14"
      - "sparkw2:10.99.170.15"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == bdc03.infra.prod.f3.itc.inventec
      resources:
        limits:
          cpus: "8"
          memory: 8g

networks:
  hostnet:
    external:
      name: host