version: "3.3"
services:
  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "18080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager

networks:
  default:
    external:
      name: gpdb