version: '3'
services:

  slave:
    image: ${REGISTRY}/development/keepalived:latest
    hostname: smdw
    volumes:
      - /opt/greenplum/keepalived/volumes/keepalived.conf:/container/service/keepalived/assets/keepalived.conf:ro
      - /opt/greenplum/keepalived/volumes/checkgp.sh:/checkgp.sh
    environment:
      - KEEPALIVED_INTERFACE=enp3s0
      - KEEPALIVED_PRIORITY=90
      - KEEPALIVED_ROUTER_ID=60
      - KEEPALIVED_UNICAST_PEERS=['192.168.1.10', '192.168.1.11']
      - KEEPALIVED_VIRTUAL_IPS=10.191.6.66/22
      - HOST_IP=10.191.6.55
    network_mode: host
    cap_add:
      - NET_ADMIN
    command: --loglevel info
    restart: always