version: "3.3"
services:
  mdw:
    image: ${REGISTRY}/${TAGNAME}
    hostname: mdw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk1/gpdata/gpmaster:/data/greenplum/master
    deploy:
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: 
          - node.role == manager

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "18080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: 
          - node.role == manager

networks:
  default:
    external:
      name: gpdb
