version: "3.3"
services:

  sdw1:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw1
    volumes:
      - /disk2/greenplum/primary:/data/greenplum/primary
      - /disk2/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role != manager]
      endpoint_mode: dnsrr

  sdw2:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw2
    volumes:
      - /disk3/greenplum/primary:/data/greenplum/primary
      - /disk3/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role != manager]
      endpoint_mode: dnsrr

networks:
  default:
    external:
      name: gpdb