version: "3.3"
services:
  mdw:
    image: ${REGISTRY}/${TAGNAME}
    hostname: mdw
    ports:
      - "5432:5432"
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk1:/disk1
    deploy:
      mode: replicated
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: 
          - node.role == manager

  visualizer:
    image: ${REGISTRY}/development/visualizer:180821
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager

networks:
  default:
    external:
      name: gpdb