version: "3.3"
services:

  sdw1:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw1
    ports:
      - "5432:5432"
    volumes:
      - /disk1:/disk1
      - /disk2:/disk2
      - /disk3:/disk3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node60]
      endpoint_mode: dnsrr

  sdw2:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw2
    volumes:
      - /disk1:/disk1
      - /disk2:/disk2
      - /disk3:/disk3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node62]
      endpoint_mode: dnsrr

  sdw3:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw3
    volumes:
      - /disk1:/disk1
      - /disk2:/disk2
      - /disk3:/disk3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node64]
      endpoint_mode: dnsrr

  sdw4:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw4
    volumes:
      - /disk1:/disk1
      - /disk2:/disk2
      - /disk3:/disk3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node66]
      endpoint_mode: dnsrr

  sdw5:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw5
    volumes:
      - /disk1:/disk1
      - /disk2:/disk2
      - /disk3:/disk3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node68]
      endpoint_mode: dnsrr

networks:
  default:
    external:
      name: gpdb