version: "3.3"
services:

  sdw1:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw1
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk1/greenplum/primary:/data/greenplum/primary
      - /disk1/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node60]
      endpoint_mode: dnsrr

  sdw2:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw2
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk1/greenplum/primary:/data/greenplum/primary
      - /disk1/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node62]
      endpoint_mode: dnsrr

  sdw3:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw3
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk1/greenplum/primary:/data/greenplum/primary
      - /disk1/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node64]
      endpoint_mode: dnsrr

  sdw4:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw4
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk1/greenplum/primary:/data/greenplum/primary
      - /disk1/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node66]
      endpoint_mode: dnsrr

  sdw5:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw5
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk1/greenplum/primary:/data/greenplum/primary
      - /disk1/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node68]
      endpoint_mode: dnsrr

  sdw6:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw6
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk2/greenplum/primary:/data/greenplum/primary
      - /disk2/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node60]
      endpoint_mode: dnsrr

  sdw7:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw7
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk2/greenplum/primary:/data/greenplum/primary
      - /disk2/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node62]
      endpoint_mode: dnsrr  

  sdw8:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw8
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk2/greenplum/primary:/data/greenplum/primary
      - /disk2/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node64]
      endpoint_mode: dnsrr

  sdw9:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw9
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk2/greenplum/primary:/data/greenplum/primary
      - /disk2/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node66]
      endpoint_mode: dnsrr

  sdw10:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw10
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk2/greenplum/primary:/data/greenplum/primary
      - /disk2/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node68]
      endpoint_mode: dnsrr

  sdw11:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw11
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk3/greenplum/primary:/data/greenplum/primary
      - /disk3/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node60]
      endpoint_mode: dnsrr

  sdw12:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw12
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk3/greenplum/primary:/data/greenplum/primary
      - /disk3/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node62]
      endpoint_mode: dnsrr

  sdw13:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw13
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk3/greenplum/primary:/data/greenplum/primary
      - /disk3/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node64]
      endpoint_mode: dnsrr

  sdw14:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw14
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk3/greenplum/primary:/data/greenplum/primary
      - /disk3/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node66]
      endpoint_mode: dnsrr

  sdw15:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sdw15
    volumes:
      - /opt/greenplum/config:/opt/greenplum/config
      - /disk3/greenplum/primary:/data/greenplum/primary
      - /disk3/greenplum/mirror:/data/greenplum/mirror
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.labels.alias == node68]
      endpoint_mode: dnsrr

networks:
  default:
    external:
      name: gpdb