version: '2.3'
services:

  prometheus:
    image: prom/prometheus:v2.13.1
    container_name: prometheus
    hostname: prometheus
    network_mode: host
    # ports:
    #   - "9090:9090"
    volumes:
      - ./config:/config:ro
    command:
      - --config.file=/config/prometheus.yml
      - --web.enable-lifecycle
    restart: always
    # cpu_count: 2
    # mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    
  grafana:
    image: grafana/grafana:6.4.4
    container_name: grafana
    hostname: grafana
    network_mode: host
    # ports:
    #   - "3000:3000"
    restart: always
    # cpu_count: 2
    # mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  
  redis-exporter:
    image: oliver006/redis_exporter:v1.3.4
    container_name: redis-exporter
    hostname: redis-exporter
    network_mode: host
    # ports:
    #   - "9121:9121"
    environment:
      REDIS_ADDR: redis://172.21.0.10:6379
    restart: always
    # cpu_count: 2
    # mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# docker run -d \
#   --net="host" \
#   --pid="host" \
#   -v "/:/host:ro,rslave" \
#   quay.io/prometheus/node-exporter \
#   --path.rootfs=/host