version: "3.3"
services:
  sparkmaster:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkmaster
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8081:8081
    volumes:
      - /opt/sparkv2/tasks:/opt/tasks
      - /disk6/spark/spark-events:/tmp/spark-events
    environment:
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
      SPARK_MASTER_WEBUI_PORT: 8081
    deploy:
      mode: replicated
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: 
          - node.role == manager

networks:
  default:
    external:
      name: gpdb