version: "3.3"
services:
  sparkmaster:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkmaster
    ports:
      - target: 4040
        published: 4040
        protocol: tcp
        mode: host
      - target: 6066
        published: 6066
        protocol: tcp
        mode: host
      - target: 7077
        published: 7077
        protocol: tcp
        mode: host
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    volumes:
      - /opt/sparkv2/tasks:/opt/tasks
    environment:
      SPARK_PUBLIC_DNS: 10.99.170.58
      SPARK_MASTER_WEBUI_PORT: 8081
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == node58

networks:
  default:
    external:
      name: gpdb