version: "3.3"
services:
  sparkworker:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkworker
    ports:
      - 8081:8081
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role != manager]

networks:
  default:
    external:
      name: gpdb