version: "3.3"
services:

  sparkw1:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkw1
    ports:
      - target: 18081
        published: 18081
        protocol: tcp
        mode: host
      - target: 18082
        published: 18082
        protocol: tcp
        mode: host
    environment:
      SPARK_WORKER_INSTANCES: 2
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_PUBLIC_DNS: 10.99.170.60
      SPARK_WORKER_WEBUI_PORT: 18081
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == node60
  
  sparkw2:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkw2
    ports:
      - target: 18081
        published: 18081
        protocol: tcp
        mode: host
      - target: 18082
        published: 18082
        protocol: tcp
        mode: host
    environment:
      SPARK_WORKER_INSTANCES: 2
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_PUBLIC_DNS: 10.99.170.62
      SPARK_WORKER_WEBUI_PORT: 18081
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == node62

networks:
  default:
    external:
      name: gpdb