akhq:
  connections:
    dev:
      properties:
        bootstrap.servers: 10.191.5.218:9092
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="bdc" password="bdcinfra";'
      connect:
        - name: connect-1
          url: http://10.191.6.53:8083
    ipt:
      connect:
        - name: connect-1
          url: http://10.99.173.216:8083