# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - 10.191.5.218:9092
  sasl:
    enabled: true
    mechanism: PLAIN
    username: bdc
    password: bdcinfra

# server:
  # listenPort: 8080