version: '3.3'
services:
  
  zookeeper:
    image: harbor.inventec.com/hub/zookeeper:3.5.5
    ports:
      - "2181:2181"
  
  kafka01:
    image: harbor.inventec.com/hub/wurstmeister/kafka:2.12-2.0.1
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - /disk/kafka:/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/kafka-logs-01
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.191.5.218:9092
      KAFKA_LOG_CLEANUP_POLICY: delete,compact
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 21474836480
      # KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 86400000
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_HEAP_OPTS: -Xmx2g -Xms2g
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == bdc01.infra.dev.tj.itc.inventec
      resources:
        limits:
          cpus: "2"
          memory: 2g

  kafka02:
    image: harbor.inventec.com/hub/wurstmeister/kafka:2.12-2.0.1
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - /disk/kafka:/kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LOG_DIRS: /kafka/kafka-logs-02
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.191.5.233:9092
      KAFKA_LOG_CLEANUP_POLICY: delete,compact
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 21474836480
      # KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 86400000
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_HEAP_OPTS: -Xmx2g -Xms2g
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == bdc03.infra.dev.tj.itc.inventec
      resources:
        limits:
          cpus: "2"
          memory: 2g

  kafka03:
    image: harbor.inventec.com/hub/wurstmeister/kafka:2.12-2.0.1
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - /disk/kafka:/kafka
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LOG_DIRS: /kafka/kafka-logs-03
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.191.4.54:9092
      KAFKA_LOG_CLEANUP_POLICY: delete,compact
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 21474836480
      # KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 86400000
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_HEAP_OPTS: -Xmx2g -Xms2g
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == bdc04.infra.dev.tj.itc.inventec
      resources:
        limits:
          cpus: "2"
          memory: 2g

  kafka-manager:
    image: harbor.inventec.com/hub/hlebalbau/kafka-manager:2.0.0.2
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    command: -Dpidfile.path=/dev/null

  cassandra-sink-connector:
    image: harbor.inventec.com/hub/streamreactor/cassandra:1.2.0
    ports:
      - "8083:8083"
    environment:
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_BOOTSTRAP_SERVERS: kafka01:9092,kafka02:9092,kafka03:9092
      CONNECT_GROUP_ID: spi_test_gp
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_REST_ADVERTISED_HOST_NAME: cassandra-sink-connector
      CONNECT_REST_PORT: 8083
      CONNECTOR_NAME: cassandra-sink-f6-spi
      CONNECTOR_CONNECTOR_CLASS: com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector
      CONNECTOR_TASKS_MAX: 1
      CONNECTOR_TOPICS: f6-spilog
      CONNECTOR_CONNECT_CASSANDRA_KCQL: INSERT INTO spi_test SELECT * FROM f6-spilog
      CONNECTOR_CONNECT_CASSANDRA_CONTACT_POINTS: 10.191.6.44,10.191.5.238
      CONNECTOR_CONNECT_CASSANDRA_PORT: 9042
      CONNECTOR_CONNECT_CASSANDRA_KEY_SPACE: spi_f6
      CONNECTOR_CONNECT_CASSANDRA_CONSISTENCY_LEVEL: QUORUM
      CONNECTOR_CONNECT_CASSANDRA_ERROR_POLICY: THROW
      SECRETS_PROVIDER: env
      SECRET_CONNECT_CASSANDRA_PASSORD: ""
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.labels.alias == bdc03.infra.dev.tj.itc.inventec
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2"
          memory: 2g

networks:
  default:
    external:
      name: gpdb5
