version: '3.4'
services:
  
  zoo1:
    image: ${REGISTRY}/hub/zookeeper:3.4.13
    hostname: zoo1
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    volumes:
      - /disk/zookeeper/data:/data
      - /disk/zookeeper/datalog:/datalog
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == bdc02.infra.dev.tj.itc.inventec
      resources:
        limits:
          cpus: "2"
          memory: 4g

networks:
  default:
    external:
      name: gpdb5
