version: "3.3"
services:

  sparkw1:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkw1
    volumes:
      - /disk6/spark:/tmp
    environment:
      SPARK_WORKER_CORES: 16
      SPARK_WORKER_MEMORY: 16g
      SPARK_PUBLIC_DNS: 10.99.170.60
      SPARK_WORKER_WEBUI_PORT: 18081
      SPARK_LOCAL_DIRS: /tmp
    networks:
      hostnet: {}
    extra_hosts:
      - "sparkmaster:10.99.170.64"
      - "sparkw1:10.99.170.60"
      - "sparkw2:10.99.170.62"
      - "sparkw3:10.99.170.66"
      - "sparkw4:10.99.170.68"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == node60
  
  sparkw2:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkw2
    volumes:
      - /disk6/spark:/tmp
    environment:
      SPARK_WORKER_CORES: 16
      SPARK_WORKER_MEMORY: 16g
      SPARK_PUBLIC_DNS: 10.99.170.62
      SPARK_WORKER_WEBUI_PORT: 18081
      SPARK_LOCAL_DIRS: /tmp
    networks:
      hostnet: {}
    extra_hosts:
      - "sparkmaster:10.99.170.64"
      - "sparkw1:10.99.170.60"
      - "sparkw2:10.99.170.62"
      - "sparkw3:10.99.170.66"
      - "sparkw4:10.99.170.68"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == node62

  sparkw3:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkw3
    volumes:
      - /disk6/spark:/tmp
    environment:
      SPARK_WORKER_CORES: 16
      SPARK_WORKER_MEMORY: 16g
      SPARK_PUBLIC_DNS: 10.99.170.66
      SPARK_WORKER_WEBUI_PORT: 18081
      SPARK_LOCAL_DIRS: /tmp
    networks:
      hostnet: {}
    extra_hosts:
      - "sparkmaster:10.99.170.64"
      - "sparkw1:10.99.170.60"
      - "sparkw2:10.99.170.62"
      - "sparkw3:10.99.170.66"
      - "sparkw4:10.99.170.68"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == node66

  sparkw4:
    image: ${REGISTRY}/${TAGNAME}
    hostname: sparkw4
    volumes:
      - /disk6/spark:/tmp
    environment:
      SPARK_WORKER_CORES: 16
      SPARK_WORKER_MEMORY: 16g
      SPARK_PUBLIC_DNS: 10.99.170.68
      SPARK_WORKER_WEBUI_PORT: 18081
      SPARK_LOCAL_DIRS: /tmp
    networks:
      hostnet: {}
    extra_hosts:
      - "sparkmaster:10.99.170.64"
      - "sparkw1:10.99.170.60"
      - "sparkw2:10.99.170.62"
      - "sparkw3:10.99.170.66"
      - "sparkw4:10.99.170.68"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.alias == node68

networks:
  hostnet:
    external:
      name: host